services:
  badminton:
    image: badminton-count:latest
    ports:
      - "48020:18080"
    environment:
      - DATABASE_PATH=/data/badminton.db
    volumes:
      - /tmp/zfsv3/nvme12/13263199088/data/Docker/badminton/data:/data
    restart: unless-stopped
